<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Handle Robots.txt generation and related functionality
 */

class SEO_Setup_Robots_Txt {
    public static function init() {
        add_action('wp_ajax_generate_robots_txt', [__CLASS__, 'seo_setup_generate_robots_txt_callback']);

        // Also keep our filter if we want to add lines dynamically
        add_filter('robots_txt', [__CLASS__, 'filter_robots_txt'], 10, 2);
    }

    public static function seo_setup_generate_robots_txt_callback() {
        check_ajax_referer('seo_setup_nonce', 'nonce');
        if (!current_user_can('manage_options')) {
            wp_send_json_error(array('message' => 'Unauthorized request.'));
        }

        // (A) LOG start of robots.txt generation
        seo_setup_logger_robots_txt_start();

        // Build robots.txt content
        $site_url = site_url();
        $robots_content = "# Robots.txt file generated by SEO Setup Plugin\n";
        $robots_content .= "# " . current_time('mysql') . "\n\n";
        
        $robots_content .= "User-agent: *\n";
        $robots_content .= "Disallow: /wp-admin/\n";
        $robots_content .= "Allow: /wp-admin/admin-ajax.php\n";
        $robots_content .= "Disallow: /wp-login.php\n";
        $robots_content .= "Disallow: /wp-includes/\n";
        $robots_content .= "Disallow: /private/\n";
        $robots_content .= "Disallow: /cgi-bin/\n";
        $robots_content .= "Allow: /wp-content/uploads/\n";
        $robots_content .= "Allow: /wp-content/plugins/\n";
        $robots_content .= "Allow: /wp-content/themes/\n\n";

        $robots_content .= "# Block specific bots from certain paths\n";
        $robots_content .= "User-agent: MJ12bot\n";
        $robots_content .= "Disallow: /\n\n";

        $robots_content .= "# Sitemap URLs\n";
        $robots_content .= "Sitemap: " . $site_url . "/sitemap.xml\n";
        $robots_content .= "Sitemap: " . $site_url . "/image-sitemap.xml\n";

        // Save robots.txt in WordPress root directory
        $robots_path = ABSPATH . 'robots.txt';

        // FIXED: Check both directory AND existing file writability
        if ( ! seo_setup_ensure_directory_writable( ABSPATH ) ) {
            wp_send_json_error(array('message' => 'WordPress root directory is not writable. Please ask your hosting provider to set correct permissions on: ' . ABSPATH));
            return;
        }
        if ( file_exists( $robots_path ) && ! is_writable( $robots_path ) ) {
            @chmod( $robots_path, 0644 );
            if ( ! is_writable( $robots_path ) ) {
                wp_send_json_error(array('message' => 'The existing robots.txt file is not writable. Please check file ownership and permissions.'));
                return;
            }
        }

        $result = file_put_contents($robots_path, $robots_content);
        if ($result === false) {
            wp_send_json_error(array('message' => 'Failed to save robots.txt file.'));
            return;
        }

        @chmod($robots_path, 0644);

        // FIXED: Log BEFORE sending JSON response (wp_send_json_success calls wp_die)
        // Logging is now non-blocking so it won't delay the response
        seo_setup_logger_robots_txt_completed($robots_content);

        $robots_url = site_url('/robots.txt');

        wp_send_json_success(array(
            'message'         => 'Robots.txt file generated successfully',
            'robots_txt_url'  => $robots_url,
            'robots_txt_content' => $robots_content,
        ));
    }

    public static function filter_robots_txt($output, $public) {
        // If site is not public, do not add lines
        if ($public != 1) {
            return $output;
        }
        $home_url = home_url();
        $output  .= "\n# SEO Setup Plugin Additional Lines\n";
        $output  .= "Sitemap: {$home_url}/sitemap.xml\n";
        $output  .= "Sitemap: {$home_url}/image-sitemap.xml\n";

        return $output;
    }
}

/**
 * ----------------------------------------------------
 * LOGGING FUNCTIONS FOR ROBOTS.TXT
 * ----------------------------------------------------
 */
if (!function_exists('seo_setup_logger_robots_txt_start')) {
    function seo_setup_logger_robots_txt_start() {
        $pinfo = seo_setup_get_plugin_info();
        $sinfo = seo_setup_get_site_user_info();

        $payload = array(
            'plugin-name' => $pinfo['name'],
            'version'     => $pinfo['version'],
            'website'     => $sinfo['website'],
            'username'    => $sinfo['username'],
            'date-time'   => seo_setup_get_current_ist_datetime(),
            'type'        => 'SEO Setup Robots.txt Generation Start',
            'data'        => array(
                'message' => 'User triggered Robots.txt generation.',
            ),
        );
        seo_setup_send_api_log($payload);
    }
}

if (!function_exists('seo_setup_logger_robots_txt_completed')) {
    function seo_setup_logger_robots_txt_completed($robots_content) {
        $pinfo = seo_setup_get_plugin_info();
        $sinfo = seo_setup_get_site_user_info();

        $payload = array(
            'plugin-name' => $pinfo['name'],
            'version'     => $pinfo['version'],
            'website'     => $sinfo['website'],
            'username'    => $sinfo['username'],
            'date-time'   => seo_setup_get_current_ist_datetime(),
            'type'        => 'SEO Setup Robots.txt Generation Complete',
            'data'        => array(
                'message'        => 'Robots.txt successfully written.',
                'robots_content' => $robots_content,
            ),
        );
        seo_setup_send_api_log($payload);
    }
}
